config: dev-2019052202

---
server:
  port: 48081
spring:
  profiles: client01
...
---
server:
  port: 48082
spring:
  profiles: client02
...
---
server:
  port: 48083
spring:
  profiles: client03
...
