spring:
  application:
    name: wom-eureka-service  #应用名称

eureka:
  server:
    enable-self-preservation: false #开发阶段可以通过配置关闭自我保护模式
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

---
spring:
  profiles: eureka01

server:
  port: 38081 #端口

eureka:
  instance:
    hostname: eureka-01 #实例主机名称
  client:
    service-url:
      defaultZone: http://eureka-02:38082/eureka/,http://eureka-03:38083/eureka/
...
---
spring:
  profiles: eureka02

server:
  port: 38082  #端口

eureka:
  instance:
    hostname: eureka-02
  client:
    service-url:
      defaultZone: http://eureka-01:38081/eureka/,http://eureka-03:38083/eureka/
...
---
spring:
  profiles: eureka03

server:
  port: 38083  #端口

eureka:
  instance:
    hostname: eureka-03
  client:
    service-url:
      defaultZone: http://eureka-01:38081/eureka/,http://eureka-02:38082/eureka/
...
